In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Seaborn style
sns.set_theme(style="whitegrid")

In [4]:
df = pd.read_csv('AmazonSalesData.csv')
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

In [5]:
df.shape

(100, 14)

In [6]:
df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

In [7]:
df.dtypes

Region             object
Country            object
Item Type          object
Sales Channel      object
Order Priority     object
Order Date         object
Order ID            int64
Ship Date          object
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          100 non-null    object
 1   Country         100 non-null    object
 2   Item Type       100 non-null    object
 3   Sales Channel   100 non-null    object
 4   Order Priority  100 non-null    object
 5   Order Date      100 non-null    object
 6   Order ID        100 non-null    int64
 7   Ship Date       100 non-null    object
 8   Units Sold      100 non-null    int64
 9   Unit Price      100 non-null    float64
 10  Unit Cost       100 non-null    float64
 11  Total Revenue   100 non-null    float64
 12  Total Cost      100 non-null    float64
 13  Total Profit    100 non-null    float64
dtypes: float64(5), int64(2), object(7)
memory usage: 11.1+ KB

In [9]:
df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+02,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
mean,5.550204e+08,5128.710000,276.761300,191.048000,1.373488e+06,9.318057e+05,4.416820e+05
std,2.606153e+08,2794.484562,235.592241,188.208181,1.460029e+06,1.083938e+06,4.385379e+05
min,1.146066e+08,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,3.389225e+08,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05
50%,5.577086e+08,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05
75%,7.907551e+08,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05
max,9.940222e+08,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06

In [10]:
df.describe(include='object')

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Ship Date
count,100,100,100,100,100,100,100
unique,7,76,12,2,4,100,99
top,Sub-Saharan Africa,The Gambia,Cosmetics,Offline,H,5/28/2010,11/17/2010
freq,36,4,13,50,30,1,2

In [11]:
df['Region'].value_counts()

Region
Sub-Saharan Africa                   36
Europe                               22
Australia and Oceania                11
Asia                                 11
Middle East and North Africa         10
Central America and the Caribbean     7
North America                         3
Name: count, dtype: int64

In [12]:
df['Item Type'].value_counts()

Item Type
Cosmetics          13
Clothes            13
Office Supplies    12
Fruits             10
Personal Care      10
Household           9
Beverages           8
Cereal              7
Baby Food           7
Vegetables          6
Snacks              3
Meat                2
Name: count, dtype: int64

In [13]:
df['Sales Channel'].value_counts()

Sales Channel
Offline    50
Online     50
Name: count, dtype: int64

In [14]:
df['Order Priority'].value_counts()

Order Priority
H    30
L    27
C    22
M    21
Name: count, dtype: int64

In [15]:
df.isnull().sum()

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [16]:
missing_percentage = df.isnull().mean() * 100

missing_percentage.sort_values(ascending=False)

Region            0.0
Country           0.0
Item Type         0.0
Sales Channel     0.0
Order Priority    0.0
Order Date        0.0
Order ID          0.0
Ship Date         0.0
Units Sold        0.0
Unit Price        0.0
Unit Cost         0.0
Total Revenue     0.0
Total Cost        0.0
Total Profit      0.0
dtype: float64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df['Order ID'].duplicated().sum()

np.int64(0)

In [19]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [20]:
df.dtypes

Region                    object
Country                   object
Item Type                 object
Sales Channel             object
Order Priority            object
Order Date        datetime64[ns]
Order ID                   int64
Ship Date         datetime64[ns]
Units Sold                 int64
Unit Price               float64
Unit Cost                float64
Total Revenue            float64
Total Cost               float64
Total Profit             float64
dtype: object

In [22]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Month Name'] = df['Order Date'].dt.month_name()
df['Quarter'] = df['Order Date'].dt.quarter

In [23]:
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Year,Month,Month Name,Quarter
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-05-28,669165933,2010-06-27,9925,255.28,159.42,2533654.00,1582243.50,951410.50,2010,5,May,2
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-08-22,963881480,2012-09-15,2804,205.70,117.11,576782.80,328376.44,248406.36,2012,8,August,3
2,Europe,Russia,Office Supplies,Offline,L,2014-05-02,341417157,2014-05-08,1779,651.21,524.96,1158502.59,933903.84,224598.75,2014,5,May,2
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-06-20,514321792,2014-07-05,8102,9.33,6.92,75591.66,56065.84,19525.82,2014,6,June,2
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-02-01,115456712,2013-02-06,5062,651.21,524.96,3296425.02,2657347.52,639077.50,2013,2,February,1
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-04,547995746,2015-02-21,2974,255.28,159.42,759202.72,474115.08,285087.64,2015,2,February,1
6,Sub-Saharan Africa,Angola,Household,Offline,M,2011-04-23,135425221,2011-04-27,4187,668.27,502.54,2798046.49,2104134.98,693911.51,2011,4,April,2
7,Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,2012-07-17,871543967,2012-07-27,8082,154.06,90.93,1245112.92,734896.26,510216.66,2012,7,July,3
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-07-14,770463311,2015-08-25,6070,81.73,56.67,496101.10,343986.90,152114.20,2015,7,July,3
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,2014-04-18,616607081,2014-05-30,6593,205.70,117.11,1356180.10,772106.23,584073.87,2014,4,April,2
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-06-24,814711606,2011-07-12,124,154.06,90.93,19103.44,11275.32,7828.12,2011,6,June,2
11,Sub-Saharan Africa,Cape Verde,Clothes,Offline,H,2014-08-02,939825713,2014-08-19,4168,109.28,35.84,455479.04,149381.12,306097.92,2014,8,August,3
12,Asia,Bangladesh,Clothes,Online,L,2017-01-13,187310731,2017-03-01,8263,109.28,35.84,902980.64,296145.92,606834.72,2017,1,January,1
13,Central America and the Caribbean,Honduras,Household,Offline,H,2017-02-08,522840487,2017-02-13,8974,668.27,502.54,5997054.98,4509793.96,1487261.02,2017,2,February,1
14,Asia,Mongolia,Personal Care,Offline,C,2014-02-19,832401311,2014-02-23,4901,81.73,56.67,400558.73,277739.67,122819.06,2014,2,February,1
15,Europe,Bulgaria,Clothes,Online,M,2012-04-23,972292029,2012-06-03,1673,109.28,35.84,182825.44,59960.32,122865.12,2012,4,April,2
16,Asia,Sri Lanka,Cosmetics,Offline,M,2016-11-19,419123971,2016-12-18,6952,437.20,263.33,3039414.40,1830670.16,1208744.24,2016,11,November,4
17,Sub-Saharan Africa,Cameroon,Beverages,Offline,C,2015-04-01,519820964,2015-04-18,5430,47.45,31.79,257653.50,172619.70,85033.80,2015,4,April,2
18,Asia,Turkmenistan,Household,Offline,L,2010-12-30,441619336,2011-01-20,3830,668.27,502.54,2559474.10,1924728.20,634745.90,2010,12,December,4
19,Australia and Oceania,East Timor,Meat,Online,L,2012-07-31,322067916,2012-09-11,5908,421.89,364.69,2492526.12,2154588.52,337937.60,2012,7,July,3
20,Europe,Norway,Baby Food,Online,L,2014-05-14,819028031,2014-06-28,7450,255.28,159.42,1901836.00,1187679.00,714157.00,2014,5,May,2
21,Europe,Portugal,Baby Food,Online,H,2015-07-31,860673511,2015-09-03,1273,255.28,159.42,324971.44,202941.66,122029.78,2015,7,July,3
22,Central America and the Caribbean,Honduras,Snacks,Online,L,2016-06-30,795490682,2016-07-26,2225,152.58,97.44,339490.50,216804.00,122686.50,2016,6,June,2
23,Australia and Oceania,New Zealand,Fruits,Online,H,2014-09-08,142278373,2014-10-04,2187,9.33,6.92,20404.71,15134.04,5270.67,2014,9,September,3
24,Europe,Moldova,Personal Care,Online,L,2016-05-07,740147912,2016-05-10,5070,81.73,56.67,414371.10,287316.90,127054.20,2016,5,May,2
25,Europe,France,Cosmetics,Online,H,2017-05-22,898523128,2017-06-05,1815,437.20,263.33,793518.00,477943.95,315574.05,2017,5,May,2
26,Australia and Oceania,Kiribati,Fruits,Online,M,2014-10-13,347140347,2014-11-10,5398,9.33,6.92,50363.34,37354.16,13009.18,2014,10,October,4
27,Sub-Saharan Africa,Mali,Fruits,Online,L,2010-05-07,686048400,2010-05-10,5822,9.33,6.92,54319.26,40288.24,14031.02,2010,5,May,2
28,Europe,Norway,Beverages,Offline,C,2014-07-18,435608613,2014-07-30,5124,47.45,31.79,243133.80,162891.96,80241.84,2014,7,July,3
29,Sub-Saharan Africa,The Gambia,Household,Offline,L,2012-05-26,886494815,2012-06-09,2370,668.27,502.54,1583799.90,1191019.80,392780.10,2012,5,May,2
30,Europe,Switzerland,Cosmetics,Offline,M,2012-09-17,249693334,2012-10-20,8661,437.20,263.33,3786589.20,2280701.13,1505888.07,2012,9,September,3
31,Sub-Saharan Africa,South Sudan,Personal Care,Offline,C,2013-12-29,406502997,2014-01-28,2125,81.73,56.67,173676.25,120423.75,53252.50,2013,12,December,4
32,Australia and Oceania,Australia,Office Supplies,Online,C,2015-10-27,158535134,2015-11-25,2924,651.21,524.96,1904138.04,1534983.04,369155.00,2015,10,October,4
33,Asia,Myanmar,Household,Offline,H,2015-01-16,177713572,2015-03-01,8250,668.27,502.54,5513227.50,4145955.00,1367272.50,2015,1,January,1
34,Sub-Saharan Africa,Djibouti,Snacks,Online,M,2017-02-25,756274640,2017-02-25,7327,152.58,97.44,1117953.66,713942.88,404010.78,2017,2,February,1
35,Central America and the Caribbean,Costa Rica,Personal Care,Offline,L,2017-05-08,456767165,2017-05-21,6409,81.73,56.67,523807.57,363198.03,160609.54,2017,5,May,2
36,Middle East and North Africa,Syria,Fruits,Online,L,2011-11-22,162052476,2011-12-03,3784,9.33,6.92,35304.72,26185.28,9119.44,2011,11,November,4
37,Sub-Saharan Africa,The Gambia,Meat,Online,M,2017-01-14,825304400,2017-01-23,4767,421.89,364.69,2011149.63,1738477.23,272672.40,2017,1,January,1
38,Asia,Brunei,Office Supplies,Online,L,2012-04-01,320009267,2012-05-08,6708,651.21,524.96,4368316.68,3521431.68,846885.00,2012,4,April,2
39,Europe,Bulgaria,Office Supplies,Online,M,2012-02-16,189965903,2012-02-28,3987,651.21,524.96,2596374.27,2093015.52,503358.75,2012,2,February,1
40,Sub-Saharan Africa,Niger,Personal Care,Online,H,2017-03-11,699285638,2017-03-28,3015,81.73,56.67,246415.95,170860.05,75555.90,2017,3,March,1
41,Middle East and North Africa,Azerbaijan,Cosmetics,Online,M,2010-02-06,382392299,2010-02-25,7234,437.20,263.33,3162704.80,1904929.22,1257775.58,2010,2,February,1
42,Sub-Saharan Africa,The Gambia,Cereal,Offline,H,2012-06-07,994022214,2012-06-08,2117,205.70,117.11,435466.90,247921.87,187545.03,2012,6,June,2
43,Europe,Slovakia,Vegetables,Online,H,2012-10-06,759224212,2012-11-10,171,154.06,90.93,26344.26,15549.03,10795.23,2012,10,October,4
44,Asia,Myanmar,Clothes,Online,H,2015-11-14,223359620,2015-11-18,5930,109.28,35.84,648030.40,212531.20,435499.20,2015,11,November,4
45,Sub-Saharan Africa,Comoros,Cereal,Offline,H,2016-03-29,902102267,2016-04-29,962,205.70,117.11,197883.40,112659.82,85223.58,2016,3,March,1
46,Europe,Iceland,Cosmetics,Online,C,2016-12-31,331438481,2016-12-31,8867,437.20,263.33,3876652.40,2334947.11,1541705.29,2016,12,December,4
47,Europe,Switzerland,Personal Care,Online,M,2010-12-23,617667090,2011-01-31,273,81.73,56.67,22312.29,15470.91,6841.38,2010,12,December,4
48,Europe,Macedonia,Clothes,Offline,C,2014-10-14,787399423,2014-11-14,7842,109.28,35.84,856973.76,281057.28,575916.48,2014,10,October,4
49,Sub-Saharan Africa,Mauritania,Office Supplies,Offline,C,2012-01-11,837559306,2012-01-13,1266,651.21,524.96,824431.86,664599.36,159832.50,2012,1,January,1
50,Europe,Albania,Clothes,Online,C,2010-02-02,385383069,2010-03-18,2269,109.28,35.84,247956.32,81320.96,166635.36,2010,2,February,1
51,Sub-Saharan Africa,Lesotho,Fruits,Online,L,2013-08-18,918419539,2013-09-18,9606,9.33,6.92,89623.98,66473.52,23150.46,2013,8,August,3
52,Middle East and North Africa,Saudi Arabia,Cereal,Online,M,2013-03-25,844530045,2013-03-28,4063,205.70,117.11,835759.10,475817.93,359941.17,2013,3,March,1
53,Sub-Saharan Africa,Sierra Leone,Office Supplies,Offline,M,2011-11-26,441888415,2012-01-07,3457,651.21,524.96,2251232.97,1814786.72,436446.25,2011,11,November,4
54,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Offline,H,2013-09-17,508980977,2013-10-24,7637,9.33,6.92,71253.21,52848.04,18405.17,2013,9,September,3
55,Sub-Saharan Africa,Cote d'Ivoire,Clothes,Online,C,2012-06-08,114606559,2012-06-27,3482,109.28,35.84,380512.96,124794.88,255718.08,2012,6,June,2
56,Australia and Oceania,Fiji,Clothes,Offline,C,2010-06-30,647876489,2010-08-01,9905,109.28,35.84,1082418.40,354995.20,727423.20,2010,6,June,2
57,Europe,Austria,Cosmetics,Offline,H,2015-02-23,868214595,2015-03-02,2847,437.20,263.33,1244708.40,749700.51,495007.89,2015,2,February,1
58,Europe,United Kingdom,Household,Online,L,2012-01-05,955357205,2012-02-14,282,668.27,502.54,188452.14,141716.28,46735.86,2012,1,January,1
59,Sub-Saharan Africa,Djibouti,Cosmetics,Offline,H,2014-04-07,259353148,2014-04-19,7215,437.20,263.33,3154398.00,1899925.95,1254472.05,2014,4,April,2
60,Australia and Oceania,Australia,Cereal,Offline,H,2013-06-09,450563752,2013-07-02,682,205.70,117.11,140287.40,79869.02,60418.38,2013,6,June,2
61,Europe,San Marino,Baby Food,Online,L,2013-06-26,569662845,2013-07-01,4750,255.28,159.42,1212580.00,757245.00,455335.00,2013,6,June,2
62,Sub-Saharan Africa,Cameroon,Office Supplies,Online,M,2011-11-07,177636754,2011-11-15,5518,651.21,524.96,3593376.78,2896729.28,696647.50,2011,11,November,4
63,Middle East and North Africa,Libya,Clothes,Offline,H,2010-10-30,705784308,2010-11-17,6116,109.28,35.84,668356.48,219197.44,449159.04,2010,10,October,4
64,Central America and the Caribbean,Haiti,Cosmetics,Offline,H,2013-10-13,505716836,2013-11-16,1705,437.20,263.33,745426.00,448977.65,296448.35,2013,10,October,4
65,Sub-Saharan Africa,Rwanda,Cosmetics,Offline,H,2013-10-11,699358165,2013-11-25,4477,437.20,263.33,1957344.40,1178928.41,778415.99,2013,10,October,4
66,Sub-Saharan Africa,Gabon,Personal Care,Offline,L,2012-07-08,228944623,2012-07-09,8656,81.73,56.67,707454.88,490535.52,216919.36,2012,7,July,3
67,Central America and the Caribbean,Belize,Clothes,Offline,M,2016-07-25,807025039,2016-09-07,5498,109.28,35.84,600821.44,197048.32,403773.12,2016,7,July,3
68,Europe,Lithuania,Office Supplies,Offline,H,2010-10-24,166460740,2010-11-17,8287,651.21,524.96,5396577.27,4350343.52,1046233.75,2010,10,October,4
69,Sub-Saharan Africa,Madagascar,Clothes,Offline,L,2015-04-25,610425555,2015-05-28,7342,109.28,35.84,802333.76,263137.28,539196.48,2015,4,April,2
70,Asia,Turkmenistan,Office Supplies,Online,M,2013-04-23,462405812,2013-05-20,5010,651.21,524.96,3262562.10,2630049.60,632512.50,2013,4,April,2
71,Middle East and North Africa,Libya,Fruits,Online,L,2015-08-14,816200339,2015-09-30,673,9.33,6.92,6279.09,4657.16,1621.93,2015,8,August,3
72,Sub-Saharan Africa,Democratic Republic of the Congo,Beverages,Online,C,2011-05-26,585920464,2011-07-15,5741,47.45,31.79,272410.45,182506.39,89904.06,2011,5,May,2
73,Sub-Saharan Africa,Djibouti,Cereal,Online,H,2017-05-20,555990016,2017-06-17,8656,205.70,117.11,1780539.20,1013704.16,766835.04,2017,5,May,2
74,Middle East and North Africa,Pakistan,Cosmetics,Offline,L,2013-07-05,231145322,2013-08-16,9892,437.20,263.33,4324782.40,2604860.36,1719922.04,2013,7,July,3
75,North America,Mexico,Household,Offline,C,2014-11-06,986435210,2014-12-12,6954,668.27,502.54,4647149.58,3494663.16,1152486.42,2014,11,November,4
76,Australia and Oceania,Federated States of Micronesia,Beverages,Online,C,2014-10-28,217221009,2014-11-15,9379,47.45,31.79,445033.55,298158.41,146875.14,2014,10,October,4
77,Asia,Laos,Vegetables,Offline,C,2011-09-15,789176547,2011-10-23,3732,154.06,90.93,574951.92,339350.76,235601.16,2011,9,September,3
78,Europe,Monaco,Baby Food,Offline,H,2012-05-29,688288152,2012-06-02,8614,255.28,159.42,2198981.92,1373243.88,825738.04,2012,5,May,2
79,Australia and Oceania,Samoa,Cosmetics,Online,H,2013-07-20,670854651,2013-08-07,9654,437.20,263.33,4220728.80,2542187.82,1678540.98,2013,7,July,3
80,Europe,Spain,Household,Offline,L,2012-10-21,213487374,2012-11-30,4513,668.27,502.54,3015902.51,2267963.02,747939.49,2012,10,October,4
81,Middle East and North Africa,Lebanon,Clothes,Online,L,2012-09-18,663110148,2012-10-08,7884,109.28,35.84,861563.52,282562.56,579000.96,2012,9,September,3
82,Middle East and North Africa,Iran,Cosmetics,Online,H,2016-11-15,286959302,2016-12-08,6489,437.20,263.33,2836990.80,1708748.37,1128242.43,2016,11,November,4
83,Sub-Saharan Africa,Zambia,Snacks,Online,L,2011-01-04,122583663,2011-01-05,4085,152.58,97.44,623289.30,398042.40,225246.90,2011,1,January,1
84,Sub-Saharan Africa,Kenya,Vegetables,Online,L,2012-03-18,827844560,2012-04-07,6457,154.06,90.93,994765.42,587135.01,407630.41,2012,3,March,1
85,North America,Mexico,Personal Care,Offline,L,2012-02-17,430915820,2012-03-20,6422,81.73,56.67,524870.06,363934.74,160935.32,2012,2,February,1
86,Sub-Saharan Africa,Sao Tome and Principe,Beverages,Offline,C,2011-01-16,180283772,2011-01-21,8829,47.45,31.79,418936.05,280673.91,138262.14,2011,1,January,1
87,Sub-Saharan Africa,The Gambia,Baby Food,Offline,M,2014-02-03,494747245,2014-03-20,5559,255.28,159.42,1419101.52,886215.78,532885.74,2014,2,February,1
88,Middle East and North Africa,Kuwait,Fruits,Online,M,2012-04-30,513417565,2012-05-18,522,9.33,6.92,4870.26,3612.24,1258.02,2012,4,April,2
89,Europe,Slovenia,Beverages,Offline,C,2016-10-23,345718562,2016-11-25,4660,47.45,31.79,221117.00,148141.40,72975.60,2016,10,October,4
90,Sub-Saharan Africa,Sierra Leone,Office Supplies,Offline,H,2016-12-06,621386563,2016-12-14,948,651.21,524.96,617347.08,497662.08,119685.00,2016,12,December,4
91,Australia and Oceania,Australia,Beverages,Offline,H,2014-07-07,240470397,2014-07-11,9389,47.45,31.79,445508.05,298476.31,147031.74,2014,7,July,3
92,Middle East and North Africa,Azerbaijan,Office Supplies,Online,M,2012-06-13,423331391,2012-07-24,2021,651.21,524.96,1316095.41,1060944.16,255151.25,2012,6,June,2
93,Europe,Romania,Cosmetics,Online,H,2010-11-26,660643374,2010-12-25,7910,437.20,263.33,3458252.00,2082940.30,1375311.70,2010,11,November,4
94,Central America and the Caribbean,Nicaragua,Beverages,Offline,C,2011-02-08,963392674,2011-03-21,8156,47.45,31.79,387002.20,259279.24,127722.96,2011,2,February,1
95,Sub-Saharan Africa,Mali,Clothes,Online,M,2011-07-26,512878119,2011-09-03,888,109.28,35.84,97040.64,31825.92,65214.72,2011,7,July,3
96,Asia,Malaysia,Fruits,Offline,L,2011-11-11,810711038,2011-12-28,6267,9.33,6.92,58471.11,43367.64,15103.47,2011,11,November,4
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-01,728815257,2016-06-29,1485,154.06,90.93,228779.10,135031.05,93748.05,2016,6,June,2
98,North America,Mexico,Personal Care,Offline,M,2015-07-30,559427106,2015-08-08,5767,81.73,56.67,471336.91,326815.89,144521.02,2015,7,July,3
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2012-02-10,665095412,2012-02-15,5367,668.27,502.54,3586605.09,2697132.18,889472.91,2012,2,February,1